### ISSUE TITLE
Add a BinaryBuilder for Normaliz

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz.jl#1]
... so that people can use Normaliz.jl w/o compiling it; and so that installation is super fast.

This binarybuilder then could possibly also used by GAP.jl, for the GAP package `NormalizInterface`. 

It could then also leverage existing BinaryBuilders for flint, GMP, etc (maybe for arb, e-antic, cocoa, nauty, one should add separate BinaryBuilder, too...)

**Comment by benlorenz** [comment]
I have normaliz 3.7.4 built here https://github.com/benlorenz/normalizBuilder/releases for the old BinaryBuilder format.
Version 3.8.4 had some build-problems that I fixed for the new BinaryBuilder Pkg-Artifacts, pull request for Yggdrasil is open which would allow just writing ']add normaliz_jll':
https://github.com/JuliaPackaging/Yggdrasil/pull/625
You can test it with `dev https://github.com/benlorenz/normaliz_jll.jl` and `using normaliz_jll` which should then provide a path for `libnormaliz`.

* It uses the julia-gmp but I have not looked at the other dependencies.
* Windows support is disabled because I had several issues with GMP and `long long` there.

**Comment by fingolfin** [comment]
As Benjamin already indicated, these days we really should instead switch to using [normaliz_jll](https://github.com/JuliaBinaryWrappers/normaliz_jll.jl), which is generated from <https://github.com/JuliaPackaging/Yggdrasil/blob/master/N/normaliz/build_tarballs.jl>.

It is currently a bit behind, but we can easily update it to a more recent version; more annoying is probably that it currently us built without e-antic and cocoa support, but that could also be resolved, by adding an JLLs for those? Although... I am not sure how that would in turn interact with Antic_jll, which we also use (I am a bit fuzzy on the relation between  antic and e-antic).

**Comment by w-bruns** [comment]
Let me point out that Normaliz can now be compiled for MS Windows (see https://github.com/Normaliz/Normaliz/releases/tag/v3.9.2 ) with all optional packages under MSYS2 MinGW64. At least I can produce a static normaliz.exe that only links kernel DLLs at runtime. I am quite sure that also dynamic versions are possible and that an expert could produce it.
